plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://reasoning-machine.github.io
baseurl: /oaio

title: Reasoning Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Reasoning-Machine
  verb: Reasoning
  instructions_file: reasoning.txt
  token: openai
  server: https://localhost:443
  apiUrl: https://api.openai.com/v1/responses

app:
  worker_name: oaioapi.js

lm:
  model: gpt-5-2025-08-07
  max_output_tokens: 128001
  reasoning_effort: high
  reasoning_summary: detailed
  temperature: 1.0

github_settings:
  owner: reasoning-machine
  repo: reasoning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
